apiVersion: v1
kind: ServiceAccount
metadata:
  name: fake-lb
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fake-lb
rules:
- apiGroups: [""]
  resources: ["services", "nodes"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fake-lb
subjects:
- kind: ServiceAccount
  name: fake-lb
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: fake-lb
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-lb
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-lb
  template:
    metadata:
      labels:
        app: fake-lb
    spec:
      serviceAccountName: fake-lb
      containers:
      - name: fake-lb
        image: spurin/fake-lb:latest
        imagePullPolicy: Always
      restartPolicy: Always
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
